apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: citysort

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
