apiVersion: v1
kind: Secret
metadata:
  name: citysort-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: ""
  AZURE_DOCUMENT_INTELLIGENCE_API_KEY: ""
