apiVersion: v1
kind: Service
metadata:
  name: citysort
  labels:
    app: citysort
spec:
  selector:
    app: citysort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
